### ISSUE TITLE
Cannot compile on 4.4.0-57-generic #78-Ubuntu 16.04 32-bit

### ISSUE THREAD

**Issue by rajgole** [dbason/crystalhd#11]
Generic lubuntu 16.04 32bit install on dual core atom with latest patches.
Had to replace libgstreamermm-0.10-dev libgstreamer0.10-dev with 1.0 versions as older versions are not available.  Here are the error messages.
-------------------------------------------------------

family@jasper:~/crystalhd/driver/linux$ make -j2
make -C /lib/modules/4.4.0-57-generic/build SUBDIRS=/home/family/crystalhd/driver/linux modules
make[1]: Entering directory '/usr/src/linux-headers-4.4.0-57-generic'
  CC [M]  /home/family/crystalhd/driver/linux/crystalhd_lnx.o
  CC [M]  /home/family/crystalhd/driver/linux/crystalhd_cmds.o
/home/family/crystalhd/driver/linux/crystalhd_lnx.c: In function 'chd_pci_reserve_mem':
/home/family/crystalhd/driver/linux/crystalhd_lnx.c:541:7: error: implicit declaration of function 'check_mem_region' [-Werror=implicit-function-declaration]
  rc = check_mem_region(bar0, i2o_len);
       ^
/home/family/crystalhd/driver/linux/crystalhd_cmds.c: In function 'bc_cproc_notify_mode':
/home/family/crystalhd/driver/linux/crystalhd_cmds.c:88:47: error: comparison of constant '2' with boolean expression is always false [-Werror=bool-compare]
  if ((idata->udata.u.NotifyMode.Mode && 0xFF) == DTS_MONITOR_MODE) {
                                               ^
cc1: all warnings being treated as errors
scripts/Makefile.build:258: recipe for target '/home/family/crystalhd/driver/linux/crystalhd_lnx.o' failed
make[2]: *** [/home/family/crystalhd/driver/linux/crystalhd_lnx.o] Error 1
make[2]: *** Waiting for unfinished jobs....
cc1: all warnings being treated as errors
scripts/Makefile.build:258: recipe for target '/home/family/crystalhd/driver/linux/crystalhd_cmds.o' failed

**Comment by rajgole** [comment]
README.md  has a reference to the source from yeradis. It should be dbason.  It compiles fine now.
 
Change from 
git clone https://github.com/yeradis/crystalhd.git   

to
git clone https://github.com/dbason/crystalhd.git

**Comment by Ardakilic** [comment]
I tried installing on Lubuntu 16.04, and the dependencies were somehow missing, so I editted the line a little bit:

```
sudo apt-get install checkinstall git-core autoconf build-essential subversion dpkg-dev fakeroot pbuilder build-essential dh-make debhelper devscripts patchutils quilt git-buildpackage pristine-tar git yasm zlib1g-dev minizip libzip-dev libx11-dev libx11-dev libxv-dev vstream-client-dev libgtk2.0-dev libpulse-dev libxxf86dga-dev x11proto-xf86dga-dev git libgstreamermm-1.0-dev libgstreamer0.10-dev libgstreamer1.0-dev automake libtool python-appindicator
```

libgstreamer and zlib were missing. But I've changed zlib to minilib, and changed libgstreamer0.10 to libgstreamer1.0 and I've successfully installed on Lubuntu 16.04 with 4.4.0-57 generic kernel.

@dbason First of all, thanks for maintaining this repository! Also, how about mentioning this dependency installation changes ?
